name: mobx_resource_bloc
description: Provides tools for creating Resource Blocs whose properties work within MobX's reactivity system
version: 0.1.0
homepage: https://github.com/brianrobles204/resource_bloc

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
