name: resource_bloc
description: Bloc that manages a resources which can be backed by both a local database and a network
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: ^7.1.0
  equatable: ^2.0.3
  meta: ^1.3.0
  rxdart: ^0.27.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
