name: resource_bloc
description: Specialized Bloc for managing data backed by both local and remote sources
version: 0.1.0
homepage: https://github.com/brianrobles204/resource_bloc

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: ^7.2.0-dev.3
  equatable: ^2.0.3
  meta: ^1.3.0
  rxdart: ^0.27.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
