name: mobx_resource_bloc
description: Resource Bloc whose properties work within MobX's reactivity system
version: 0.1.0-dev.1
homepage: https://github.com/brianrobles204/resource_bloc

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: ^7.2.1
  mobx: ^2.0.5
  resource_bloc: ^0.1.0-dev.6

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0